# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'agent_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61gent_service.proto\x12\x05\x61gent\"\x1e\n\x0e\x41nalyzeRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"1\n\x0f\x41nalyzeResponse\x12\x0e\n\x06length\x18\x01 \x01(\x05\x12\x0e\n\x06status\x18\x02 \x01(\t2L\n\x0c\x41gentService\x12<\n\x0b\x41nalyzeText\x12\x15.agent.AnalyzeRequest\x1a\x16.agent.AnalyzeResponseB$\n\rcom.demo.grpcB\x11\x41gentServiceProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\rcom.demo.grpcB\021AgentServiceProtoP\001'
  _globals['_ANALYZEREQUEST']._serialized_start=30
  _globals['_ANALYZEREQUEST']._serialized_end=60
  _globals['_ANALYZERESPONSE']._serialized_start=62
  _globals['_ANALYZERESPONSE']._serialized_end=111
  _globals['_AGENTSERVICE']._serialized_start=113
  _globals['_AGENTSERVICE']._serialized_end=189
# @@protoc_insertion_point(module_scope)
